/**
 * Shared helper for calling the Anthropic API from Edge Functions and
 * parsing a JSON-only response.
 *
 * Requires ANTHROPIC_API_KEY to be set as a Supabase Edge Function
 * secret (never exposed to the client).
 */

const ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages";
const MODEL = "claude-sonnet-4-6";

// Final shared writing-quality layer. Because every module calls this helper,
// specialty-specific safeguards remain in their own prompts while the entire
// product gets the same concise, ready-to-use output standard.
const READY_TO_USE_STYLE = `

READY-TO-USE OUTPUT STYLE (applies to every PlansK12 module):
- Write for a busy educator who must scan and use the result immediately.
- Prefer short, concrete sentences, compact bullets, numbered steps, and descriptive labels over continuous paragraphs.
- Remove throat-clearing, generic encouragement, repeated objectives, repeated directions, and explanations of obvious teaching practices.
- Put the action first: what the educator does, what learners do, what to look/listen for, and when to move on.
- Keep every required standard, safety note, accommodation, clinical/professional boundary, and schema field. Concise must never mean incomplete or unsafe.
- Keep teacher-facing language professional and compact. Keep learner-facing language age-appropriate, direct, and easy to read aloud.
- Do not mention that the content was generated by AI.`;

/**
 * Calls Claude with a system+user prompt and parses the response as JSON.
 *
 * @param {string} system
 * @param {string} user
 * @param {number} [maxTokens]
 * @param {string} [model]  override the default model (e.g. a faster model for
 *   generations that must complete within a tight function time limit)
 * @param {object} [schema]  JSON Schema for structured outputs. When provided, the
 *   model is constrained to emit valid, schema-conforming JSON (no preamble, no
 *   malformed escaping). Recommended with faster/less-strict models.
 * @returns {Promise<any>}
 */
export async function callClaudeForJson(system, user, maxTokens = 4096, model = MODEL, schema = null) {
  const apiKey = Deno.env.get("ANTHROPIC_API_KEY");
  if (!apiKey) {
    throw new Error("ANTHROPIC_API_KEY is not configured");
  }

  const request = {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model,
      max_tokens: maxTokens,
      system: `${system}${READY_TO_USE_STYLE}`,
      messages: [{ role: "user", content: user }],
      // Structured outputs (GA — no beta header). Guarantees the response text is
      // valid JSON matching the schema.
      ...(schema ? { output_config: { format: { type: "json_schema", schema } } } : {}),
    }),
  };

  // Anthropic 5xx responses, including 529 overloads, are temporary. Retry
  // briefly so teachers do not have to restart an otherwise valid request.
  const retryableStatuses = new Set([500, 502, 503, 529]);
  let response;
  for (let attempt = 0; attempt < 3; attempt += 1) {
    response = await fetch(ANTHROPIC_API_URL, request);
    if (response.ok || !retryableStatuses.has(response.status) || attempt === 2) break;

    // Drain the failed response before retrying so its connection can be reused.
    await response.text();
    await new Promise((resolve) => setTimeout(resolve, attempt === 0 ? 1000 : 2500));
  }

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Anthropic API error (${response.status}): ${errText}`);
  }

  const data = await response.json();
  const textBlock = (data.content ?? []).find((block) => block.type === "text");
  if (!textBlock) {
    throw new Error("No text content returned from Anthropic API");
  }

  return parseJsonFromText(textBlock.text);
}

/**
 * Parses JSON from a model response, tolerating accidental markdown
 * code fences.
 *
 * @param {string} text
 * @returns {any}
 */
function parseJsonFromText(text) {
  let cleaned = text.trim();

  if (cleaned.startsWith("```")) {
    cleaned = cleaned
      .replace(/^```[a-zA-Z]*\n?/, "")
      .replace(/```$/, "")
      .trim();
  }

  try {
    return JSON.parse(cleaned);
  } catch (err) {
    // Some models (esp. faster ones) ignore "return ONLY JSON" and wrap the object
    // in a preamble or trailing commentary. Extract the first balanced {...} object
    // and parse that. This only runs as a fallback — clean JSON parses above.
    const extracted = extractFirstJsonObject(cleaned);
    if (extracted) {
      try {
        return JSON.parse(extracted);
      } catch {
        // fall through to the original error
      }
    }
    throw new Error(`Failed to parse model response as JSON: ${err.message}`);
  }
}

/**
 * Extracts the first complete, balanced JSON object from a string, tolerating
 * surrounding prose. Returns null if no complete object is present (e.g. the
 * response was truncated before the closing brace). Quote/escape aware so braces
 * inside string values don't throw off the depth count.
 *
 * @param {string} text
 * @returns {string | null}
 */
function extractFirstJsonObject(text) {
  const start = text.indexOf("{");
  if (start === -1) return null;
  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let i = start; i < text.length; i++) {
    const ch = text[i];
    if (inString) {
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === '"') inString = false;
    } else if (ch === '"') {
      inString = true;
    } else if (ch === "{") {
      depth++;
    } else if (ch === "}") {
      depth--;
      if (depth === 0) return text.slice(start, i + 1);
    }
  }
  return null; // no matching close brace — likely truncated
}
