import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowLeft, Check, Clipboard, Calculator, BookOpen, Loader2, Save, Sparkles } from 'lucide-react'
import FamilyNightPrintKit from '../components/intervention/FamilyNightPrintKit'
import { FAMILY_NIGHT_CONFIGS, generateFamilyNight } from '../lib/interventionFamilyNight'
import { createFamilyNightProject, listFamilyNightProjects, updateFamilyNightProject } from '../services/familyNightService'

export default function InterventionFamilyNightHub({ type }) {
  const config = FAMILY_NIGHT_CONFIGS[type]
  const [inputs, setInputs] = useState(config.defaults)
  const [plan, setPlan] = useState(() => generateFamilyNight(type, config.defaults))
  const [projects, setProjects] = useState([])
  const [savedId, setSavedId] = useState('')
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState('')
  const [copied, setCopied] = useState(false)
  const reading = type === 'reading'
  const home = `/${type}-specialists`
  const subject = reading ? 'Reading' : 'Math'
  const Icon = reading ? BookOpen : Calculator

  useEffect(() => { listFamilyNightProjects(type).then(setProjects).catch((error) => setMessage(error.message)) }, [type])

  function rebuild() { setPlan(generateFamilyNight(type, inputs)); setMessage(`${subject} night plan updated`) }
  function updateItem(sectionIndex, itemIndex, value) { setPlan((current) => ({ ...current, sections: current.sections.map((section, s) => s === sectionIndex ? { ...section, items: section.items.map((item, i) => i === itemIndex ? value : item) } : section) })) }
  function loadProject(id) { setSavedId(id); const project = projects.find((item) => item.id === id); if (!project) { setInputs(config.defaults); setPlan(generateFamilyNight(type, config.defaults)); return } setInputs(project.inputs); setPlan(project.plan); setMessage('Saved family night opened') }
  async function saveProject() { setSaving(true); setMessage(''); try { const values = { type, title: inputs.title, inputs, plan }; const saved = savedId ? await updateFamilyNightProject(savedId, values) : await createFamilyNightProject(values); setSavedId(saved.id); setProjects((current) => [saved, ...current.filter((item) => item.id !== saved.id)]); setMessage('Saved in PlansK12') } catch (error) { setMessage(error.message) } finally { setSaving(false) } }
  async function copyInvitation() { await navigator.clipboard.writeText(plan.invitation); setCopied(true); window.setTimeout(() => setCopied(false), 1500) }
  const accent = reading ? { text: 'text-sky-400', panel: 'border-sky-500/25 bg-gradient-to-br from-sky-500/20 via-blue-500/10 to-cyan-500/10', soft: 'border-sky-500/25 bg-sky-500/10', button: 'bg-sky-500 hover:bg-sky-400' } : { text: 'text-lime-400', panel: 'border-lime-500/25 bg-gradient-to-br from-lime-500/20 via-emerald-500/10 to-teal-500/10', soft: 'border-lime-500/25 bg-lime-500/10', button: 'bg-lime-500 text-ink-950 hover:bg-lime-400' }

  return <div className="space-y-7"><style>{`@media print { body * { visibility: hidden !important; } .family-night-print, .family-night-print * { visibility: visible !important; } .family-night-print { position: absolute !important; inset: 0 auto auto 0 !important; width: 100% !important; } }`}</style><div className="flex flex-wrap items-center justify-between gap-3 print:hidden"><Link to={home} className="inline-flex items-center gap-1.5 text-sm text-ink-500 hover:text-ink-200"><ArrowLeft size={14} /> {subject} Specialists workspace</Link><button type="button" onClick={saveProject} disabled={saving} className="btn-secondary">{saving ? <Loader2 size={15} className="animate-spin" /> : <Save size={15} />}{message === 'Saved in PlansK12' ? message : 'Save family night'}</button></div>
    <section className={`relative overflow-hidden rounded-3xl border p-5 print:hidden sm:p-8 ${accent.panel}`}><div className="relative flex items-start gap-4"><div className={`flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-ink-950/30 ${accent.text}`}><Icon size={28} /></div><div><p className={`text-xs font-bold uppercase tracking-[.16em] ${accent.text}`}>School-family intervention support</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-ink-50">{config.shortTitle}</h1><p className="mt-2 max-w-3xl text-sm leading-relaxed text-ink-500">Turn intervention strategies into a welcoming, schoolwide family event with hands-on stations, strengths-based language, take-home tools, and a complete printable kit.</p></div></div></section>
    <div className="grid gap-6 xl:grid-cols-[390px_minmax(0,1fr)] print:hidden"><aside className="space-y-4"><section className="card p-5"><p className="label-eyebrow">Saved {subject.toLowerCase()} nights</p><select value={savedId} onChange={(event) => loadProject(event.target.value)} className="input-field mt-3"><option value="">New family night</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.title}</option>)}</select></section><section className="card space-y-4 p-5"><div><p className="label-eyebrow">Event details</p><p className="mt-1 text-xs text-ink-500">Change any detail, then rebuild the editable plan.</p></div>{[['title','Event title'],['location','Location'],['grades','Grades'],['focus','Learning focus'],['languages','Family languages/directions']].map(([key,label]) => <label key={key} className="block text-xs font-medium text-ink-500">{label}<input value={inputs[key]} onChange={(event) => setInputs({ ...inputs, [key]: event.target.value })} className="input-field mt-1" /></label>)}<div className="grid grid-cols-2 gap-3"><label className="block text-xs font-medium text-ink-500">Date<input type="date" value={inputs.date} onChange={(event) => setInputs({ ...inputs, date: event.target.value })} className="input-field mt-1" /></label><label className="block text-xs font-medium text-ink-500">Time<input value={inputs.time} onChange={(event) => setInputs({ ...inputs, time: event.target.value })} className="input-field mt-1" /></label></div><label className="block text-xs font-medium text-ink-500">Expected families<input type="number" min="1" value={inputs.families} onChange={(event) => setInputs({ ...inputs, families: Number(event.target.value) })} className="input-field mt-1" /></label><button type="button" onClick={rebuild} className={`inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl px-4 text-sm font-bold text-white transition ${accent.button}`}><Sparkles size={16} /> Build my {subject.toLowerCase()} night</button>{message && message !== 'Saved in PlansK12' && <p className="text-center text-xs text-ink-500">{message}</p>}</section></aside>
      <main className="space-y-5"><div><p className="label-eyebrow">Editable event plan</p><p className="mt-1 text-xs text-ink-500">Every section is ready to use and still fully editable.</p></div><article className="space-y-4 rounded-3xl border border-ink-800 bg-ink-950/40 p-5 sm:p-7"><header className={`rounded-2xl border p-5 ${accent.soft}`}><p className={`text-xs font-black uppercase tracking-[.15em] ${accent.text}`}>{config.title}</p><h2 className="mt-1 text-2xl font-black text-ink-50">{plan.title}</h2><p className="mt-1 text-sm text-ink-500">{plan.subtitle}</p></header><div className="grid gap-4 lg:grid-cols-2">{plan.sections.map((section, sectionIndex) => <section key={section.title} className="rounded-2xl border border-ink-800 p-5"><h3 className={`font-bold ${accent.text}`}>{section.title}</h3><div className="mt-3 space-y-2">{section.items.map((item, itemIndex) => <textarea key={`${sectionIndex}-${itemIndex}`} value={item} onChange={(event) => updateItem(sectionIndex, itemIndex, event.target.value)} rows="2" className="min-h-0 w-full resize-y border-0 bg-transparent p-0 text-sm leading-6 text-ink-300 outline-none" />)}</div></section>)}</div></article><section className="card p-5"><div className="flex items-center justify-between gap-3"><div><p className="label-eyebrow">Family invitation</p><p className="mt-1 text-xs text-ink-500">Copy into email, text, social media, or your school newsletter.</p></div><button type="button" onClick={copyInvitation} className={`inline-flex items-center gap-1 text-xs font-bold ${accent.text}`}>{copied ? <Check size={13} /> : <Clipboard size={13} />}{copied ? 'Copied' : 'Copy'}</button></div><textarea value={plan.invitation} onChange={(event) => setPlan({ ...plan, invitation: event.target.value })} rows="9" className="input-field mt-4 resize-y text-sm leading-6" /></section></main></div>
    <FamilyNightPrintKit inputs={inputs} plan={plan} type={type} />
  </div>
}
