import { useMemo, useState } from 'react'
import { ClipboardList, FileStack, IdCard, LayoutGrid, Mail, PackageCheck, Printer } from 'lucide-react'
import { FAMILY_NIGHT_CONFIGS } from '../../lib/interventionFamilyNight'

const OPTIONS = [
  ['plan', 'Event Plan', 'Schedule, setup, staffing, and safeguards', ClipboardList],
  ['stations', 'Station Cards', 'Large facilitator directions for every station', LayoutGrid],
  ['passport', 'Family Passport', 'A friendly station-by-station activity sheet', IdCard],
  ['home', 'Take-Home Guide', 'Simple routines families can use immediately', PackageCheck],
  ['invitation', 'Invitations', 'A ready-to-share family invitation', Mail],
  ['materials', 'Materials & Volunteers', 'Shopping, setup, and helper checklists', ClipboardList],
  ['complete', 'Complete Family Night Kit', 'Every event and family printable together', FileStack],
]

function Header({ inputs, type, label }) {
  const subject = type === 'reading' ? 'Reading' : 'Math'
  return <header className={`mb-5 border-b-2 pb-3 ${type === 'reading' ? 'border-sky-500' : 'border-lime-600'}`}><p className={`text-[10px] font-black uppercase tracking-[.22em] ${type === 'reading' ? 'text-sky-700' : 'text-lime-800'}`}>PlansK12 · {subject} Intervention Family Night</p><div className="mt-1 flex items-end justify-between gap-4"><div><h2 className="text-2xl font-black text-slate-950">{inputs.title}</h2><p className="mt-1 text-xs font-semibold text-slate-600">{inputs.date || 'Date coming soon'} · {inputs.time} · {inputs.location}</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${type === 'reading' ? 'bg-sky-100 text-sky-900' : 'bg-lime-100 text-lime-950'}`}>{label}</span></div></header>
}

function EventPlan({ inputs, plan, type }) { return <section className="kit-sheet"><Header inputs={inputs} type={type} label="Event plan" /><div className="grid grid-cols-2 gap-4">{plan.sections.map((section) => <section key={section.title} className="kit-panel"><h3>{section.title}</h3><ul className="mt-3 space-y-2 text-xs leading-5 text-slate-700">{section.items.map((item) => <li key={item}>• {item}</li>)}</ul></section>)}</div></section> }

function StationCards({ inputs, type }) { const config = FAMILY_NIGHT_CONFIGS[type]; return <section className="kit-sheet"><Header inputs={inputs} type={type} label="Station cards" /><div className="grid grid-cols-2 gap-5">{config.stations.map(([title, description], index) => <article key={title} className="kit-cut-card min-h-64"><p className={`text-xs font-black uppercase tracking-[.2em] ${type === 'reading' ? 'text-sky-700' : 'text-lime-800'}`}>Station {index + 1}</p><h3 className="mt-2 text-xl font-black text-slate-950">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-700">{description}</p><div className="mt-4 rounded-xl bg-slate-100 p-3 text-xs text-slate-800"><strong>Facilitator:</strong> Model one example, invite family practice, then ask, “What strategy did you notice?”</div><p className="mt-4 text-xs font-bold text-slate-800">At home we could: __________________________________</p></article>)}</div></section> }

function Passport({ inputs, type }) { const config = FAMILY_NIGHT_CONFIGS[type]; return <section className="kit-sheet"><Header inputs={inputs} type={type} label="Family passport" /><div className="grid grid-cols-2 gap-4">{config.stations.map(([title], index) => <section key={title} className="kit-panel min-h-36"><p className={`text-[10px] font-black uppercase ${type === 'reading' ? 'text-sky-700' : 'text-lime-800'}`}>Stop {index + 1}</p><h3 className="mt-1">{title}</h3><p className="mt-4 text-xs text-slate-700">Our favorite strategy or idea:</p><div className="mt-2 h-10 border-b border-slate-300" /><p className="mt-3 text-xs">Family initials: __________________</p></section>)}</div><section className={`mt-5 rounded-2xl border-2 p-4 ${type === 'reading' ? 'border-sky-300 bg-sky-50' : 'border-lime-400 bg-lime-50'}`}><h3 className="font-black text-slate-950">Our one-week family goal</h3><p className="mt-3 text-sm text-slate-800">This week, we will ________________________________________________ on __________________ days.</p></section></section> }

function HomeGuide({ inputs, type }) { const config = FAMILY_NIGHT_CONFIGS[type]; return <section className="kit-sheet"><Header inputs={inputs} type={type} label="Take-home guide" /><h3 className="text-2xl font-black text-slate-950">Small routines. Real growth. No special supplies.</h3><div className="mt-5 grid grid-cols-2 gap-4">{config.homeTips.map((tip, index) => <section key={tip} className="kit-panel"><p className={`text-xs font-black uppercase ${type === 'reading' ? 'text-sky-700' : 'text-lime-800'}`}>Try this {index + 1}</p><p className="mt-2 text-sm leading-6 text-slate-800">{tip}</p></section>)}</div><section className="mt-5 kit-panel"><h3>A simple weekly rhythm</h3><p className="mt-3 text-sm leading-6 text-slate-700">Choose a comfortable 10–15 minute time. Let your child choose an activity, try one strategy together, ask them to explain their thinking, and end by naming something that went well.</p><p className="mt-4 text-xs font-bold text-slate-800">Questions for the interventionist: _________________________________________________</p></section></section> }

function Invitation({ inputs, plan, type }) { return <section className="kit-sheet"><Header inputs={inputs} type={type} label="Family invitation" /><div className={`mx-auto mt-12 max-w-2xl rounded-[2rem] border-4 p-10 text-center ${type === 'reading' ? 'border-sky-400 bg-sky-50' : 'border-lime-500 bg-lime-50'}`}><p className={`text-xs font-black uppercase tracking-[.25em] ${type === 'reading' ? 'text-sky-700' : 'text-lime-800'}`}>You’re invited</p><h3 className="mt-4 text-4xl font-black text-slate-950">{inputs.title}</h3><p className="mt-5 whitespace-pre-line text-base leading-8 text-slate-700">{plan.invitation}</p><p className="mt-7 font-black text-slate-900">Hands-on · Family friendly · Take-home tools</p></div></section> }

function Materials({ inputs, plan, type }) { const sections = plan.sections.filter((section) => ['Materials', 'Volunteer roles', 'Interventionist safeguards'].includes(section.title)); return <section className="kit-sheet"><Header inputs={inputs} type={type} label="Materials & volunteers" /><div className="grid grid-cols-2 gap-5">{sections.map((section) => <section key={section.title} className="kit-panel"><h3>{section.title}</h3>{section.items.map((item) => <p key={item} className="mt-3 text-xs leading-5 text-slate-700">□ {item}</p>)}</section>)}<section className="kit-panel"><h3>Event-day assignments</h3>{['Welcome table', 'Family navigator', 'Station facilitators', 'Materials runner', 'Take-home table', 'Cleanup team'].map((role) => <p key={role} className="mt-4 border-b border-slate-300 pb-1 text-xs text-slate-700">{role}: __________________________</p>)}</section></div></section> }

function Printable({ active, inputs, plan, type }) {
  const pages = { plan: <EventPlan inputs={inputs} plan={plan} type={type} />, stations: <StationCards inputs={inputs} type={type} />, passport: <Passport inputs={inputs} type={type} />, home: <HomeGuide inputs={inputs} type={type} />, invitation: <Invitation inputs={inputs} plan={plan} type={type} />, materials: <Materials inputs={inputs} plan={plan} type={type} /> }
  if (active === 'complete') return <>{Object.values(pages)}</>
  return pages[active]
}

export default function FamilyNightPrintKit({ inputs, plan, type }) {
  const [active, setActive] = useState('plan')
  const activeOption = useMemo(() => OPTIONS.find(([key]) => key === active), [active])
  const badgeClass = type === 'reading' ? 'bg-sky-500/15 text-sky-400' : 'bg-lime-500/15 text-lime-400'
  return <section className="space-y-5"><div className="card p-5 print:hidden"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="label-eyebrow">Ready-to-print family night kit</p><h2 className="mt-1 text-xl font-black text-ink-50">Everything needed to put the event into action</h2><p className="mt-2 text-sm text-ink-500">Preview one resource or print the complete kit as a PDF.</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${badgeClass}`}>7 printable choices</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{OPTIONS.map(([key, title, description, Icon]) => <button key={key} type="button" onClick={() => setActive(key)} aria-label={title} aria-pressed={active === key} className={`min-h-28 rounded-2xl border p-4 text-left transition ${active === key ? (type === 'reading' ? 'border-sky-400 bg-sky-500/15' : 'border-lime-400 bg-lime-500/15') : 'border-ink-800 bg-ink-950/60 hover:border-ink-600'}`}><span className="flex items-start gap-3"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${badgeClass}`}><Icon size={20} /></span><span><span className="block text-sm font-black text-ink-50">{title}</span><span className="mt-1 block text-xs leading-relaxed text-ink-500">{description}</span></span></span></button>)}</div><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-bold text-ink-100">Preview: {activeOption[1]}</p><button type="button" onClick={() => window.print()} className="btn-primary"><Printer size={16} /> Print or save PDF</button></div></div><article className="family-night-print overflow-x-auto rounded-3xl border border-ink-800 bg-white p-5 sm:p-8 print:overflow-visible print:rounded-none print:border-0 print:p-0"><div className="mx-auto min-w-[720px] max-w-[850px] print:min-w-0 print:max-w-none"><Printable active={active} inputs={inputs} plan={plan} type={type} /></div></article></section>
}
