let rows = []
let checkIns = []
export async function listStaffWellnessChallenges() { return structuredClone(rows) }
export async function createStaffWellnessChallenge(values) { const row = { id: `wellness-${rows.length + 1}`, title: values.title, template_id: values.templateId, public_token: values.publicToken, accepting_submissions: true, settings: structuredClone(values.settings), participants: structuredClone(values.participants), progress: structuredClone(values.progress), bingo: structuredClone(values.bingo), messages: structuredClone(values.messages), updated_at: new Date().toISOString() }; rows = [row, ...rows]; return structuredClone(row) }
export async function updateStaffWellnessChallenge(id, values) { const row = rows.find((item) => item.id === id); Object.assign(row, structuredClone(values), { updated_at: new Date().toISOString() }); return structuredClone(row) }
export async function listStaffWellnessCheckIns(challengeId) { return structuredClone(checkIns.filter((item) => item.challenge_id === challengeId).sort((a, b) => b.submitted_at.localeCompare(a.submitted_at))) }
export async function approveStaffWellnessCheckIn(id) { const row = checkIns.find((item) => item.id === id); row.status = 'approved'; return structuredClone(row) }
export async function getPublicStaffWellnessChallenge(token) { const row = rows.find((item) => item.public_token === token); if (!row) throw new Error('This check-in link is not available.'); return structuredClone({ id: row.id, title: row.title, settings: row.settings, bingo: row.bingo, teams: [...new Set(row.participants.map((item) => item.team))], accepting_submissions: row.accepting_submissions }) }
export async function submitStaffWellnessCheckIn(token, values) { const challenge = rows.find((item) => item.public_token === token); if (!challenge?.accepting_submissions) throw new Error('This challenge is not accepting submissions.'); const row = { id: `checkin-${checkIns.length + 1}`, challenge_id: challenge.id, participant_label: values.name, team_label: values.team, amount: Number(values.amount), activity_type: values.activity, status: 'pending', submitted_at: new Date().toISOString() }; checkIns = [row, ...checkIns]; return structuredClone(row) }
