import { useState } from 'react'
import { FileStack, Grid3X3, Mail, Megaphone, Printer, Sparkles, Users } from 'lucide-react'

const OPTIONS = [
  { key: 'poster', title: 'Challenge Poster', desc: 'A ready-to-post invitation with dates, goal, and inclusive options', Icon: Megaphone },
  { key: 'bingo', title: 'Wellness Bingo Card', desc: 'A complete 5×5 card with a free-choice center', Icon: Grid3X3 },
  { key: 'directions', title: 'Staff Directions', desc: 'How to participate, log progress, adapt activities, and protect privacy', Icon: Users },
  { key: 'messages', title: 'Communication Kit', desc: 'Launch email, reminder, and results message', Icon: Mail },
  { key: 'celebration', title: 'Results Celebration', desc: 'Aggregate progress display without exposing personal data', Icon: Sparkles },
  { key: 'complete', title: 'Complete Wellness Kit', desc: 'All printable materials in one PDF', Icon: FileStack },
]

function Header({ challenge, label }) {
  return <header className="mb-5 flex items-end justify-between gap-4 border-b-4 border-emerald-500 pb-3"><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-emerald-700">PlansK12 · Staff Wellness Challenge</p><h2 className="mt-1 text-2xl font-black text-slate-950">{challenge.title}</h2><p className="mt-1 text-xs font-semibold text-slate-600">{challenge.settings.startsOn}–{challenge.settings.endsOn} · {challenge.settings.level} · {challenge.settings.category}</p></div><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-900">{label}</span></header>
}

function Poster({ challenge }) {
  const s = challenge.settings
  return <section className="wellness-sheet"><Header challenge={challenge} label="Challenge poster" /><article className="flex min-h-[760px] flex-col items-center justify-center rounded-[36px] border-4 border-emerald-400 bg-gradient-to-br from-emerald-50 via-teal-50 to-sky-50 p-12 text-center"><p className="text-sm font-black uppercase tracking-[.3em] text-emerald-700">You’re invited</p><h3 className="mt-6 text-5xl font-black leading-tight text-slate-950">{challenge.title}</h3><p className="mt-5 max-w-xl text-xl leading-relaxed text-slate-700">{s.blurb}</p><div className="mt-8 grid w-full grid-cols-3 gap-4"><div className="wellness-stat"><strong>{s.goal}</strong><span>{s.unit}</span></div><div className="wellness-stat"><strong>{s.level}</strong><span>challenge level</span></div><div className="wellness-stat"><strong>{s.scope}</strong><span>participation</span></div></div><div className="mt-8 rounded-2xl bg-white/80 p-5 text-left"><p className="text-xs font-black uppercase tracking-wider text-emerald-700">Every level belongs</p><p className="mt-2 text-sm leading-6 text-slate-700">{s.alternative}</p></div><p className="mt-8 text-base font-black text-slate-900">{s.startsOn} through {s.endsOn}</p><p className="mt-2 text-sm text-slate-600">Progress, choice, and consistency—not perfection.</p></article></section>
}

function Bingo({ challenge }) {
  return <section className="wellness-sheet"><Header challenge={challenge} label="Wellness bingo" /><div className="mb-3 flex items-center justify-between text-xs text-slate-700"><p>Name or team: __________________________________</p><p>□ One line &nbsp; □ Four corners &nbsp; □ Full card</p></div><div className="grid grid-cols-5 border-l-2 border-t-2 border-emerald-500">{challenge.bingo.map((square, index) => <div key={`${square}-${index}`} className={`flex min-h-[128px] items-center justify-center border-b-2 border-r-2 border-emerald-500 p-2 text-center text-xs font-bold leading-4 text-slate-800 ${index === 12 ? 'bg-emerald-100 text-emerald-900' : 'bg-white'}`}>{square}</div>)}</div><p className="mt-4 text-xs leading-5 text-slate-600">Adapt any square to your needs. Seated, lower-impact, recovery, and personally appropriate alternatives count. Follow medical guidance and school policies.</p></section>
}

function Directions({ challenge }) {
  const s = challenge.settings
  return <section className="wellness-sheet"><Header challenge={challenge} label="Staff directions" /><div className="grid grid-cols-2 gap-4"><section className="wellness-panel"><h3>How it works</h3>{[`Choose personally appropriate actions connected to ${challenge.title}.`, `Log progress in ${s.unit}; the shared goal is ${s.goal}.`, 'Use a bingo card for variety or follow the main challenge.', 'Celebrate consistency and encourage coworkers without comparing bodies or ability.'].map((item) => <p key={item}>□ {item}</p>)}</section><section className="wellness-panel"><h3>Inclusive participation</h3><p>□ {s.alternative}</p><p>□ Adapt duration, intensity, position, equipment, or environment.</p><p>□ Recovery, mobility, mindfulness, and connection may count when included.</p><p>□ Never exercise through pain or ignore medical guidance.</p></section><section className="wellness-panel"><h3>Privacy</h3><p>□ Individual results are visible only to the organizer.</p><p>□ Public updates use aggregate school or team totals.</p><p>□ No weight, BMI, diagnoses, sleep totals, calorie data, or other health details are collected.</p><p>□ The individual leaderboard is {s.leaderboard === 'off' ? 'turned off' : s.leaderboard}.</p></section><section className="wellness-panel"><h3>Ways to participate</h3><p>□ Individual progress toward a personal goal</p><p>□ Department or team contribution</p><p>□ Schoolwide collective goal</p><p>□ Wellness bingo or choose-your-own pathway</p></section></div></section>
}

function Messages({ challenge }) {
  return <section className="wellness-sheet"><Header challenge={challenge} label="Communication kit" /><div className="space-y-4">{[['Launch email',challenge.messages.launch],['Mid-challenge reminder',challenge.messages.reminder],['Results message',challenge.messages.results]].map(([title, text]) => <section key={title} className="wellness-panel"><h3>{title}</h3><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-700">{text}</p></section>)}</div></section>
}

function Celebration({ challenge, total, participantCount }) {
  const percent = challenge.settings.goal ? Math.min(100, Math.round((total / challenge.settings.goal) * 100)) : 0
  return <section className="wellness-sheet"><Header challenge={challenge} label="Results celebration" /><article className="flex min-h-[760px] flex-col items-center justify-center rounded-[36px] border-4 border-emerald-400 bg-gradient-to-br from-emerald-50 via-teal-50 to-amber-50 p-12 text-center"><p className="text-sm font-black uppercase tracking-[.3em] text-emerald-700">Together we achieved</p><p className="mt-8 text-7xl font-black text-slate-950">{total}</p><p className="mt-2 text-xl font-bold text-slate-700">{challenge.settings.unit}</p><div className="mt-8 h-7 w-full overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${percent}%` }} /></div><p className="mt-3 text-sm font-bold text-slate-700">{percent}% of our shared goal · {participantCount} participating staff members</p><h3 className="mt-10 text-3xl font-black text-slate-950">Every contribution counted.</h3><p className="mt-3 max-w-xl text-lg leading-relaxed text-slate-700">We practiced consistency, choice, encouragement, and wellness that fits real people. Thank you for supporting one another!</p></article></section>
}

function View({ active, challenge, total, participantCount }) {
  const views = { poster: <Poster challenge={challenge} />, bingo: <Bingo challenge={challenge} />, directions: <Directions challenge={challenge} />, messages: <Messages challenge={challenge} />, celebration: <Celebration challenge={challenge} total={total} participantCount={participantCount} /> }
  return active === 'complete' ? <>{views.poster}{views.bingo}{views.directions}{views.messages}{views.celebration}</> : views[active]
}

export default function StaffWellnessPrintKit({ challenge, total, participantCount }) {
  const [active, setActive] = useState('poster')
  const option = OPTIONS.find((item) => item.key === active) ?? OPTIONS[0]
  return <section className="space-y-5 print:contents"><style>{`
    .wellness-panel { border: 1px solid #cbd5e1; border-radius: 16px; padding: 18px; color: #0f172a; }
    .wellness-panel h3 { font-size: 16px; font-weight: 900; color: #0f172a; }
    .wellness-panel > p:not(.mt-3) { margin-top: 10px; font-size: 12px; line-height: 1.5; color: #334155; }
    .wellness-stat { display: flex; flex-direction: column; gap: 4px; border-radius: 16px; background: white; padding: 18px; box-shadow: 0 1px 2px #0001; }
    .wellness-stat strong { font-size: 22px; color: #0f172a; } .wellness-stat span { font-size: 11px; color: #64748b; }
    @media print { @page { size: letter portrait; margin: .42in; } .staff-wellness-print, .staff-wellness-print * { visibility: visible !important; } .staff-wellness-print { position: absolute !important; inset: 0 auto auto 0 !important; width: 100% !important; background: white !important; } .wellness-sheet { min-height: 9.65in; break-after: page; background: white !important; } .wellness-sheet:last-child { break-after: auto; } }
  `}</style><div className="print:hidden"><div className="rounded-3xl border border-emerald-500/25 bg-gradient-to-br from-emerald-500/15 via-teal-500/10 to-sky-500/5 p-5 sm:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="label-eyebrow text-emerald-400">Your Staff Wellness Kit</p><h2 className="mt-1 text-2xl font-black text-ink-50">Launch, encourage, and celebrate</h2><p className="mt-2 max-w-2xl text-sm text-ink-500">Print pieces separately or save the complete program kit as one PDF.</p></div><span className="rounded-full bg-emerald-500/15 px-3 py-1 text-xs font-bold text-emerald-400">6 printable choices</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{OPTIONS.map(({ key, title, desc, Icon }) => <button key={key} type="button" aria-label={title} aria-pressed={active === key} onClick={() => setActive(key)} className={`min-h-28 rounded-2xl border p-4 text-left transition ${active === key ? 'border-emerald-400 bg-emerald-500/15' : 'border-ink-800 bg-ink-950/60 hover:border-emerald-500/35'}`}><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-emerald-500/15 text-emerald-400"><Icon size={20} /></span><span><span className="block text-sm font-black text-ink-50">{title}</span><span className="mt-1 block text-xs leading-relaxed text-ink-500">{desc}</span></span></div></button>)}</div></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div><p className="label-eyebrow">Printable preview</p><p className="mt-1 text-sm font-bold text-ink-100">{option.title}</p></div><button type="button" onClick={() => window.print()} className="btn-primary"><Printer size={16} /> Print {option.title.toLowerCase()} or save PDF</button></div></div><article className="staff-wellness-print overflow-x-auto rounded-3xl border border-ink-800 bg-white p-5 shadow-sm sm:p-8 print:overflow-visible print:rounded-none print:border-0 print:p-0 print:shadow-none"><div className="mx-auto min-w-[720px] max-w-[850px] print:min-w-0 print:max-w-none"><View active={active} challenge={challenge} total={total} participantCount={participantCount} /></div></article></section>
}
