import { useMemo, useState } from 'react'
import { Award, ClipboardList, FileStack, Mail, Printer, Route, UserRoundCheck } from 'lucide-react'

const OPTIONS = [
  ['teacher', 'Teacher Setup Guide', 'Launch, track, adapt, and celebrate the program', ClipboardList],
  ['cards', 'Student Challenge Cards', 'Personal goal cards for the connected roster', Route],
  ['poster', 'Class Progress Poster', 'A name-free shared tracker for display', UserRoundCheck],
  ['family', 'Family Message', 'A clear explanation of the challenge and home support', Mail],
  ['certificates', 'Certificates', 'Personalized recognition for every participant', Award],
  ['complete', 'Complete Program Kit', 'All teacher, student, display, and family resources', FileStack],
]

function Header({ program, label }) { return <header className="mb-5 flex items-end justify-between gap-4 border-b-2 border-teal-600 pb-3"><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-teal-700">PlansK12 · {program.module_label}</p><h2 className="mt-1 text-2xl font-black text-slate-950">{program.title}</h2><p className="mt-1 text-xs font-semibold text-slate-600">{program.starts_on} – {program.ends_on}</p></div><span className="rounded-full bg-teal-100 px-3 py-1 text-xs font-black text-teal-950">{label}</span></header> }

function TeacherGuide({ program, resources }) { return <section className="kit-sheet"><Header program={program} label="Teacher setup" /><div className="grid grid-cols-2 gap-4"><section className="kit-panel"><h3>Challenge at a glance</h3><p className="mt-3 text-sm leading-6 text-slate-700">{program.settings.blurb}</p><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="font-bold text-slate-500">Goal</dt><dd>{program.goal_value} {program.metric_plural}</dd></div><div><dt className="font-bold text-slate-500">Goal style</dt><dd>{program.target_mode === 'collective' ? 'Shared total' : 'Per student'}</dd></div></dl></section><section className="kit-panel"><h3>Launch checklist</h3>{resources.teacherChecklist.map((item) => <p key={item} className="mt-3 text-xs leading-5 text-slate-700">□ {item}</p>)}</section><section className="kit-panel"><h3>Participation and adaptation</h3><p className="mt-3 text-sm leading-6 text-slate-700">Offer choices, alternate ways to demonstrate progress, and private teacher check-ins. Reward effort, growth, reflection, and contribution—not speed or public ranking.</p></section><section className="kit-panel"><h3>Celebration plan</h3><p className="mt-3 text-sm leading-6 text-slate-700">{resources.celebration}</p><p className="mt-5 text-xs font-bold text-slate-800">Celebration date: __________________________</p><p className="mt-4 text-xs font-bold text-slate-800">Materials/notes: __________________________</p></section></div></section> }

function ChallengeCards({ program, students }) { const people = students.length ? students : [{ id: 'blank', name_or_initials: 'Student' }]; return <section className="kit-sheet"><Header program={program} label="Student challenge cards" /><div className="grid grid-cols-2 gap-5">{people.map((student) => <article key={student.id} className="kit-cut-card min-h-64"><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">My {program.module_label} challenge</p><h3 className="mt-2 text-xl font-black text-slate-950">{program.title}</h3><p className="mt-2 text-sm font-bold text-slate-700">{student.name_or_initials}</p><p className="mt-4 text-sm leading-6 text-slate-700">My goal: {program.goal_value} {program.metric_plural}</p><div className="mt-4 grid grid-cols-5 gap-2">{Array.from({ length: 10 }, (_, index) => <span key={index} className="flex h-9 items-center justify-center rounded-lg border-2 border-teal-300 text-xs text-slate-400">✓</span>)}</div><p className="mt-5 text-xs font-bold text-slate-800">A strategy that helped me:</p><div className="mt-2 h-10 border-b border-slate-300" /></article>)}</div></section> }

function ProgressPoster({ program }) { return <section className="kit-sheet"><Header program={program} label="Class progress poster" /><div className="mx-auto mt-10 max-w-3xl rounded-[2rem] border-4 border-teal-500 bg-teal-50 p-10 text-center"><p className="text-sm font-black uppercase tracking-[.22em] text-teal-800">Our shared progress</p><h3 className="mt-4 text-4xl font-black text-slate-950">{program.title}</h3><p className="mt-5 text-xl text-slate-700">Together we are working toward</p><p className="mt-3 text-6xl font-black text-teal-700">{program.target_mode === 'collective' ? program.goal_value : 'GROWTH'}</p><p className="mt-2 text-2xl font-bold text-slate-800">{program.target_mode === 'collective' ? program.metric_plural : 'for every participant'}</p><div className="mt-9 h-12 overflow-hidden rounded-full border-4 border-teal-700 bg-white"><div className="h-full w-0 bg-teal-400" /></div><div className="mt-4 flex justify-between text-sm font-bold text-slate-700"><span>START</span><span>KEEP GOING!</span><span>CELEBRATE</span></div><p className="mt-8 text-sm font-semibold text-slate-600">Progress—not comparison. Student names stay off this display.</p></div></section> }

function FamilyMessage({ program, resources }) { return <section className="kit-sheet"><Header program={program} label="Family message" /><div className="mx-auto mt-10 max-w-2xl rounded-3xl border-2 border-teal-300 bg-teal-50 p-8"><p className="text-xs font-black uppercase tracking-[.2em] text-teal-800">A new {program.module_label} experience</p><h3 className="mt-3 text-3xl font-black text-slate-950">{program.title}</h3><p className="mt-5 whitespace-pre-line text-base leading-8 text-slate-700">{resources.familyMessage}</p><div className="mt-6 rounded-2xl bg-white p-5"><p className="font-black text-slate-900">How families can help</p><p className="mt-2 text-sm leading-6 text-slate-700">Ask what your student tried, what felt challenging, and what they want to try next. Encourage a realistic routine and celebrate effort. No special supplies or public score comparisons are required.</p></div><p className="mt-7 text-sm text-slate-700">Questions? _________________________________________________</p></div></section> }

function Certificates({ program, students }) { const people = students.length ? students : [{ id: 'blank', name_or_initials: 'Student Name' }]; return <>{people.map((student) => <section key={student.id} className="kit-sheet flex min-h-[720px] items-center justify-center"><div className="w-full rounded-[2.5rem] border-8 border-double border-teal-600 bg-gradient-to-br from-teal-50 via-white to-amber-50 p-12 text-center"><Award size={72} className="mx-auto text-amber-500" /><p className="mt-6 text-sm font-black uppercase tracking-[.3em] text-teal-800">Certificate of Growth & Contribution</p><h3 className="mt-8 text-5xl font-black text-slate-950">{student.name_or_initials}</h3><p className="mt-7 text-xl leading-9 text-slate-700">is recognized for meaningful participation in</p><p className="mt-4 text-3xl font-black text-teal-800">{program.title}</p><p className="mt-7 text-lg text-slate-700">Your effort, creativity, reflection, and progress made a difference.</p><div className="mt-16 grid grid-cols-2 gap-16 text-sm text-slate-700"><p className="border-t border-slate-500 pt-2">Teacher/Facilitator</p><p className="border-t border-slate-500 pt-2">Date</p></div></div></section>)}</> }

function Printable({ active, program, students, resources }) { const pages = { teacher: <TeacherGuide program={program} resources={resources} />, cards: <ChallengeCards program={program} students={students} />, poster: <ProgressPoster program={program} />, family: <FamilyMessage program={program} resources={resources} />, certificates: <Certificates program={program} students={students} /> }; if (active === 'complete') return <>{Object.values(pages)}</>; return pages[active] }

export default function SpecialtyProgramPrintKit({ program, students, resources }) {
  const [active, setActive] = useState('teacher')
  const selected = useMemo(() => OPTIONS.find(([key]) => key === active), [active])
  return <section className="space-y-5"><div className="card p-5 print:hidden"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="label-eyebrow">Create → Run → Celebrate kit</p><h2 className="mt-1 text-xl font-black text-ink-50">The materials that turn an idea into a real program</h2><p className="mt-2 text-sm text-ink-500">Preview one resource or print the complete program kit.</p></div><span className="rounded-full bg-teal-500/15 px-3 py-1 text-xs font-bold text-teal-400">6 printable choices</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{OPTIONS.map(([key,title,description,Icon]) => <button key={key} type="button" aria-label={title} aria-pressed={active === key} onClick={() => setActive(key)} className={`min-h-28 rounded-2xl border p-4 text-left transition ${active === key ? 'border-teal-400 bg-teal-500/15' : 'border-ink-800 bg-ink-950/60 hover:border-teal-500/35'}`}><span className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-teal-500/15 text-teal-400"><Icon size={20} /></span><span><span className="block text-sm font-black text-ink-50">{title}</span><span className="mt-1 block text-xs leading-relaxed text-ink-500">{description}</span></span></span></button>)}</div><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-bold text-ink-100">Preview: {selected[1]}</p><button type="button" onClick={() => window.print()} className="btn-primary"><Printer size={16} /> Print or save PDF</button></div></div><article className="specialty-program-print overflow-x-auto rounded-3xl border border-ink-800 bg-white p-5 sm:p-8 print:overflow-visible print:rounded-none print:border-0 print:p-0"><div className="mx-auto min-w-[720px] max-w-[850px] print:min-w-0 print:max-w-none"><Printable active={active} program={program} students={students} resources={resources} /></div></article></section>
}
